### ISSUE TITLE
Malwarebytes flagged several files as Malware.Heuristic.2006

### ISSUE THREAD

**Issue by JDi-Coding** [ysdragon/StreamBot#54]
Hey there,

I cloned your repository and installed Bun from the link provided on bun.sh (https://bun.sh/).

However, my Malwarebytes flagged several files from the .bin folder with the detection Malware.Heuristic.2006. The flagged files are:

    colorsupport.exe
    find-process.exe
    mime.exe
    mkdirp.exe
    node-pre.gyp.exe
    nopt.exe
    qrcode.exe
    rimraf.exe
    semver.exe
    tree-kill.exe
    tsc.exe
    tsserver.exe
    which.exe

**Comment by ysdragon** [comment]
Hi @JDi-Coding,
Bun installs packages from Node.js repositories, similar to how npm operates. The flagged files you mentioned (such as `colorsupport.exe`, `find-process.exe`, etc.) are part of the packages that Bun installs, which are commonly used in Node.js.

It's not unusual for these executables to be flagged, as they can be misidentified as potential threats due to their nature as development tools. This is often a result of heuristic detection methods.

**Comment by JDi-Coding** [comment]
Ok, thank you for the Quick Answer
