### ISSUE TITLE
Stream Youtube directly and add Cookies

### ISSUE THREAD

**Issue by Abruccii** [ysdragon/StreamBot#60]
Hey there,

i have forked the ytdl-core to fix the current Cookie Bug. Feel free to change the lib so you can configure youtube cookies for ytdl (@abrucci/ytdl-core). That way you can stream via ytdl without "Please Sign-In" Error.

Also you can Stream directly from ytdl with ffmpeg without storing the file. I currently only tested it with audio, video will come.

https://github.com/Abruccii/ytdl-core
https://github.com/Abruccii/Discord-Media-Player/blob/master/src/commands/playyt.ts

**Comment by ysdragon** [comment]
Hello @Abruccii,
Thanks for your advices.

> That way you can stream via ytdl without "Please Sign-In" Error.

Yes, I know this. However, the "Please Sign In" error occurs because the subnet is blocked by YouTube. While every user can set their own cookies, not all of them are able to do so. However, I may implement this feature in the future.

> Also you can Stream directly from ytdl with ffmpeg without storing the file

Yes, the bot was working like that before this [commit](https://github.com/ysdragon/StreamBot/commit/564354a8a499d68bc8e822e5765dee23924e6377)
